# Generated by Django 3.0.3 on 2020-07-26 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReefSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReefSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surveyDate', models.DateTimeField(verbose_name='Survey Date')),
                ('surveySite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reefviewer.ReefSite')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyUPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulatedCoralline', models.IntegerField(default=0)),
                ('brownSeaweed', models.IntegerField(default=0)),
                ('crustoseCoralline', models.IntegerField(default=0)),
                ('greenSeaweed', models.IntegerField(default=0)),
                ('none', models.IntegerField(default=0)),
                ('otherBrownSeaweed', models.IntegerField(default=0)),
                ('redSeaweed', models.IntegerField(default=0)),
                ('sessileInvertebrates', models.IntegerField(default=0)),
                ('bedrock', models.IntegerField(default=0)),
                ('boulder', models.IntegerField(default=0)),
                ('cobble', models.IntegerField(default=0)),
                ('other', models.IntegerField(default=0)),
                ('sand', models.IntegerField(default=0)),
                ('small', models.IntegerField(default=0)),
                ('medium', models.IntegerField(default=0)),
                ('large', models.IntegerField(default=0)),
                ('giant', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ReefTransect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('heading', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('depth', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('temp', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reefviewer.ReefSurvey')),
            ],
        ),
    ]
